baseURL = 'https://sweet-froyo-741890.netlify.app/'
languageCode = 'en-us'
title = 'PhD on FIRE'
theme = 'hyde'
[menu]
[[menu.main]]
  name = 'About'
  url = '/about/aboutme.md'
  weight = 20
[[menu.main]]
  name = 'Posts'
  url = '/posts'
  weight = 25
[[menu.main]]
  name = 'Resources'
  url = '/resources'
  weight = 30
[params]
description = "Angela's blog"
