baseurl = "https://phdonfire.com"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "red"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "PhD on FIRE"
    subtitle = "Angela Wu's personal blog"
    keywords = ""
    copyright = "Copyright 2021-{year} Angela Wu. All rights reserved."
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "PhD on FIRE"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 10
      [[languages.en.menu.main]]
        identifier = "Resources"
        name = "Resources"
        url = "/showcase"
        weight = 20
      [[languages.en.menu.main]]
        identifier = "Contact"
        name = "Contact me"
        url = "/contactme"
        weight = 30