baseURL = 'https://phdonfire.com/'
languageCode = 'en-us'
title = 'PhD on FIRE'
theme = 'hyde'
[menu]
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 20
[[menu.main]]
  name = 'Posts'
  url = '/posts'
  weight = 25
[[menu.main]]
  name = 'Resources'
  url = '/resources'
  weight = 30
[[menu.main]]
  name = 'Contact Me'
  url = '/contactme'
  weight = 40  
[params]
description = "Angela's blog"