baseURL = 'https://sweet-froyo-741890.netlify.app/'
languageCode = 'en-us'
title = 'PhD on FIRE'
theme = 'hyde'
sectionPagesMenu = "main"
[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 20
[[menu.main]]
  name = 'Posts'
  url = '/posts'
  weight = 25
[[menu.main]]
  name = 'Resources'
  url = '/resources'
  weight = 30
[params]
description = "Angela's blog"
